#include "cpu.h"
#include "Instruction.h"

using namespace libnes;

const uint8_t Instruction::ADDRESSING_MODE_LENGTHS[] =
{
	1,		// Implied
	2,		// Immediate
	2,		// Relative
	2,		// Zero page
	2,		// Zero page, X indexed
	2,		// Zero page, Y indexed
	3,		// Indirect
	2,		// Indirect from zero page, X pre-indexed
	2,		// Indirect from zero page, Y post-indexed
	3,		// Absolute
	3,		// Absolute, X indexed
	3,		// Absolute, Y indexed
	0,		// Invalid
};

const Instruction CPU::INSTRUCTION_MAP[] =
{
	{ 0x00, 7, ADDR_IMPL,			"BRK", &CPU::brk },
	{ 0x01, 6, ADDR_IZPX,			"ORA", &CPU::ora },
	{ 0x02, 1, ADDR_INVALID, "", NULL },
	{ 0x03, 8, ADDR_INVALID, "", NULL },
	{ 0x04, 3, ADDR_ZP,				"NOP", &CPU::nop },
	{ 0x05, 3, ADDR_ZP,				"ORA", &CPU::ora },
	{ 0x06, 5, ADDR_ZP,				"ASL", &CPU::asl },
	{ 0x07, 5, ADDR_INVALID, "", NULL },
	{ 0x08, 3, ADDR_IMPL,			"PHP", &CPU::php },
	{ 0x09, 2, ADDR_IMM,			"ORA", &CPU::ora },
	{ 0x0A, 2, ADDR_IMPL,			"ASL A", &CPU::asl_a },
	{ 0x0B, 2, ADDR_INVALID, "", NULL },
	{ 0x0C, 4, ADDR_ABS,			"NOP", &CPU::nop },
	{ 0x0D, 4, ADDR_ABS,			"ORA", &CPU::ora },
	{ 0x0E, 6, ADDR_ABS,			"ASL", &CPU::asl },
	{ 0x0F, 6, ADDR_INVALID, "", NULL },

	{ 0x10, 2, ADDR_REL,			"BPL", &CPU::branch },
	{ 0x11, 5, ADDR_IZPY,			"ORA", &CPU::ora },
	{ 0x12, 1, ADDR_INVALID, "", NULL },
	{ 0x13, 8, ADDR_INVALID, "", NULL },
	{ 0x14, 4, ADDR_ZPX,			"NOP", &CPU::nop },
	{ 0x15, 4, ADDR_ZPX,			"ORA", &CPU::ora },
	{ 0x16, 6, ADDR_ZPX,			"ASL", &CPU::asl },
	{ 0x17, 6, ADDR_INVALID, "", NULL },
	{ 0x18, 2, ADDR_IMPL,			"CLC", &CPU::clc },
	{ 0x19, 4, ADDR_ABSY,			"ORA", &CPU::ora },
	{ 0x1A, 2, ADDR_IMPL,			"NOP", &CPU::nop },
	{ 0x1B, 7, ADDR_INVALID, "", NULL },
	{ 0x1C, 4, ADDR_ABSX,			"NOP", &CPU::nop },
	{ 0x1D, 4, ADDR_ABSX,			"ORA", &CPU::ora },
	{ 0x1E, 7, ADDR_ABSX,			"ASL", &CPU::asl },
	{ 0x1F, 7, ADDR_INVALID, "", NULL },

	{ 0x20, 6, ADDR_ABS,			"JSR", &CPU::jsr },
	{ 0x21, 6, ADDR_IZPX,			"AND", &CPU::and$ },
	{ 0x22, 1, ADDR_INVALID, "", NULL },
	{ 0x23, 8, ADDR_INVALID, "", NULL },
	{ 0x24, 3, ADDR_ZP,				"BIT", &CPU::bit },
	{ 0x25, 3, ADDR_ZP,				"AND", &CPU::and$ },
	{ 0x26, 5, ADDR_ZP,				"ROL", &CPU::rol },
	{ 0x27, 5, ADDR_INVALID, "", NULL },
	{ 0x28, 4, ADDR_IMPL,			"PLP", &CPU::plp},
	{ 0x29, 2, ADDR_IMM,			"AND", &CPU::and$ },
	{ 0x2A, 2, ADDR_IMPL,			"ROL A", &CPU::rol_a },
	{ 0x2B, 2, ADDR_INVALID, "", NULL },
	{ 0x2C, 4, ADDR_ABS,			"BIT", &CPU::bit },
	{ 0x2D, 4, ADDR_ABS,			"AND", &CPU::and$ },
	{ 0x2E, 6, ADDR_ABS,			"ROL", &CPU::rol },
	{ 0x2F, 6, ADDR_INVALID, "", NULL },

	{ 0x30, 2, ADDR_REL,			"BMI", &CPU::branch },
	{ 0x31, 5, ADDR_IZPY,			"AND", &CPU::and$ },
	{ 0x32, 1, ADDR_INVALID, "", NULL },
	{ 0x33, 8, ADDR_INVALID, "", NULL },
	{ 0x34, 4, ADDR_ZPX,			"NOP", &CPU::nop },
	{ 0x35, 4, ADDR_ZPX,			"AND", &CPU::and$ },
	{ 0x36, 6, ADDR_ZPX,			"ROL", &CPU::rol },
	{ 0x37, 6, ADDR_INVALID, "", NULL },
	{ 0x38, 2, ADDR_IMPL,			"SEC", &CPU::sec },
	{ 0x39, 4, ADDR_ABSY,			"AND", &CPU::and$ },
	{ 0x3A, 2, ADDR_IMPL,			"NOP", &CPU::nop },
	{ 0x3B, 7, ADDR_INVALID, "", NULL },
	{ 0x3C, 4, ADDR_ABSX,			"NOP", &CPU::nop },
	{ 0x3D, 4, ADDR_ABSX,			"AND", &CPU::and$ },
	{ 0x3E, 7, ADDR_ABSX,			"ROL", &CPU::rol },
	{ 0x3F, 7, ADDR_INVALID, "", NULL },

	{ 0x40, 6, ADDR_IMPL,			"RTI", &CPU::rti },
	{ 0x41, 6, ADDR_IZPX,			"EOR", &CPU::eor },
	{ 0x42, 1, ADDR_INVALID, "", NULL },
	{ 0x43, 8, ADDR_INVALID, "", NULL },
	{ 0x44, 3, ADDR_ZP,				"NOP", &CPU::nop },
	{ 0x45, 3, ADDR_ZP,				"EOR", &CPU::eor },
	{ 0x46, 5, ADDR_ZP,				"LSR", &CPU::lsr },
	{ 0x47, 5, ADDR_INVALID, "", NULL },
	{ 0x48, 3, ADDR_IMPL,			"PHA", &CPU::pha },
	{ 0x49, 2, ADDR_IMM,			"EOR", &CPU::eor },
	{ 0x4A, 2, ADDR_IMPL,			"LSR A", &CPU::lsr_a },
	{ 0x4B, 2, ADDR_INVALID, "", NULL },
	{ 0x4C, 3, ADDR_ABS,			"JMP", &CPU::jmp_abs },
	{ 0x4D, 4, ADDR_ABS,			"EOR", &CPU::eor },
	{ 0x4E, 6, ADDR_ABS,			"LSR", &CPU::lsr },
	{ 0x4F, 6, ADDR_INVALID, "", NULL },

	{ 0x50, 2, ADDR_REL,			"BVC", &CPU::branch },
	{ 0x51, 5, ADDR_IZPY,			"EOR", &CPU::eor },
	{ 0x52, 1, ADDR_INVALID, "", NULL },
	{ 0x53, 8, ADDR_INVALID, "", NULL },
	{ 0x54, 4, ADDR_ZPX,			"NOP", &CPU::nop },
	{ 0x55, 4, ADDR_ZPX,			"EOR", &CPU::eor },
	{ 0x56, 6, ADDR_ZPX,			"LSR", &CPU::lsr },
	{ 0x57, 6, ADDR_INVALID, "", NULL },
	{ 0x58, 2, ADDR_IMPL,			"CLI", &CPU::cli },
	{ 0x59, 4, ADDR_ABSY,			"EOR", &CPU::eor },
	{ 0x5A, 2, ADDR_IMPL,			"NOP", &CPU::nop },
	{ 0x5B, 7, ADDR_INVALID, "", NULL },
	{ 0x5C, 4, ADDR_ABSX,			"NOP", &CPU::nop },
	{ 0x5D, 4, ADDR_ABSX,			"EOR", &CPU::eor },
	{ 0x5E, 7, ADDR_ABSX,			"LSR", &CPU::lsr },
	{ 0x5F, 7, ADDR_INVALID, "", NULL },

	{ 0x60, 6, ADDR_IMPL,			"RTS", &CPU::rts },
	{ 0x61, 6, ADDR_IZPX,			"ADC", &CPU::adc },
	{ 0x62, 1, ADDR_INVALID, "", NULL },
	{ 0x63, 8, ADDR_INVALID, "", NULL },
	{ 0x64, 3, ADDR_ZP,				"NOP", &CPU::nop },
	{ 0x65, 3, ADDR_ZP,				"ADC", &CPU::adc },
	{ 0x66, 5, ADDR_ZP,				"ROR", &CPU::ror },
	{ 0x67, 5, ADDR_INVALID, "", NULL },
	{ 0x68, 4, ADDR_IMPL,			"PLA", &CPU::pla },
	{ 0x69, 2, ADDR_IMM,			"ADC", &CPU::adc },
	{ 0x6A, 2, ADDR_IMPL,			"ROR A", &CPU::ror_a },
	{ 0x6B, 2, ADDR_INVALID, "", NULL },
	{ 0x6C, 5, ADDR_IND,			"JMP", &CPU::jmp_ind },
	{ 0x6D, 4, ADDR_ABS,			"ADC", &CPU::adc },
	{ 0x6E, 6, ADDR_ABS,			"ROR", &CPU::ror },
	{ 0x6F, 6, ADDR_INVALID, "", NULL },

	{ 0x70, 2, ADDR_REL,			"BVS", &CPU::branch },
	{ 0x71, 5, ADDR_IZPY,			"ADC", &CPU::adc },
	{ 0x72, 1, ADDR_INVALID, "", NULL },
	{ 0x73, 8, ADDR_INVALID, "", NULL },
	{ 0x74, 4, ADDR_ZPX,			"NOP", &CPU::nop },
	{ 0x75, 4, ADDR_ZPX,			"ADC", &CPU::adc },
	{ 0x76, 6, ADDR_ZPX,			"ROR", &CPU::ror },
	{ 0x77, 6, ADDR_INVALID, "", NULL },
	{ 0x78, 2, ADDR_IMPL,			"SEI", &CPU::sei },
	{ 0x79, 4, ADDR_ABSY,			"ADC", &CPU::adc },
	{ 0x7A, 2, ADDR_IMPL,			"NOP", &CPU::nop },
	{ 0x7B, 7, ADDR_INVALID, "", NULL },
	{ 0x7C, 4, ADDR_ABSX,			"NOP", &CPU::nop },
	{ 0x7D, 4, ADDR_ABSX,			"ADC", &CPU::adc },
	{ 0x7E, 7, ADDR_ABSX,			"ROR", &CPU::ror },
	{ 0x7F, 7, ADDR_INVALID, "", NULL },

	{ 0x80, 2, ADDR_IMM,			"NOP", &CPU::nop },
	{ 0x81, 6, ADDR_IZPX,			"STA", &CPU::sta },
	{ 0x82, 2, ADDR_IMM,			"NOP", &CPU::nop },
	{ 0x83, 6, ADDR_IZPX,			"SAX", &CPU::sax },
	{ 0x84, 3, ADDR_ZP,				"STY", &CPU::sty },
	{ 0x85, 3, ADDR_ZP,				"STA", &CPU::sta },
	{ 0x86, 3, ADDR_ZP,				"STX", &CPU::stx },
	{ 0x87, 3, ADDR_ZP,				"SAX", &CPU::sax },
	{ 0x88, 2, ADDR_IMPL,			"DEY", &CPU::dey },
	{ 0x89, 2, ADDR_IMM,			"NOP", &CPU::nop },
	{ 0x8A, 2, ADDR_IMPL,			"TXA", &CPU::txa },
	{ 0x8B, 2, ADDR_INVALID, "", NULL },
	{ 0x8C, 4, ADDR_ABS,			"STY", &CPU::sty },
	{ 0x8D, 4, ADDR_ABS,			"STA", &CPU::sta },
	{ 0x8E, 4, ADDR_ABS,			"STX", &CPU::stx },
	{ 0x8F, 4, ADDR_ABS,			"SAX", &CPU::sax },

	{ 0x90, 2, ADDR_REL,			"BCC", &CPU::branch },
	{ 0x91, 6, ADDR_IZPY,			"STA", &CPU::sta },
	{ 0x92, 1, ADDR_INVALID, "", NULL },
	{ 0x93, 6, ADDR_INVALID, "", NULL },
	{ 0x94, 4, ADDR_ZPX,			"STY", &CPU::sty },
	{ 0x95, 4, ADDR_ZPX,			"STA", &CPU::sta },
	{ 0x96, 4, ADDR_ZPY,			"STX", &CPU::stx },
	{ 0x97, 4, ADDR_ZPY,			"SAX", &CPU::sax },
	{ 0x98, 2, ADDR_IMPL,			"TYA", &CPU::tya },
	{ 0x99, 5, ADDR_ABSY,			"STA", &CPU::sta },
	{ 0x9A, 2, ADDR_IMPL,			"TXS", &CPU::txs },
	{ 0x9B, 5, ADDR_INVALID, "", NULL },
	{ 0x9C, 5, ADDR_INVALID, "", NULL },
	{ 0x9D, 5, ADDR_ABSX,			"STA", &CPU::sta },
	{ 0x9E, 5, ADDR_INVALID, "", NULL },
	{ 0x9F, 5, ADDR_INVALID, "", NULL },

	{ 0xA0, 2, ADDR_IMM,			"LDY", &CPU::ldy },
	{ 0xA1, 6, ADDR_IZPX,			"LDA", &CPU::lda },
	{ 0xA2, 2, ADDR_IMM,			"LDX", &CPU::ldx },
	{ 0xA3, 6, ADDR_IZPX,			"LAX", &CPU::lax },
	{ 0xA4, 3, ADDR_ZP,				"LDY", &CPU::ldy },
	{ 0xA5, 3, ADDR_ZP,				"LDA", &CPU::lda },
	{ 0xA6, 3, ADDR_ZP,				"LDX", &CPU::ldx },
	{ 0xA7, 3, ADDR_ZP,				"LAX", &CPU::lax },
	{ 0xA8, 2, ADDR_IMPL,			"TAY", &CPU::tay },
	{ 0xA9, 2, ADDR_IMM,			"LDA", &CPU::lda },
	{ 0xAA, 2, ADDR_IMPL,			"TAX", &CPU::tax },
	{ 0xAB, 2, ADDR_INVALID, "", NULL },
	{ 0xAC, 4, ADDR_ABS,			"LDY", &CPU::ldy },
	{ 0xAD, 4, ADDR_ABS,			"LDA", &CPU::lda },
	{ 0xAE, 4, ADDR_ABS,			"LDX", &CPU::ldx },
	{ 0xAF, 4, ADDR_ABS,			"LAX", &CPU::lax },

	{ 0xB0, 2, ADDR_REL,			"BCS", &CPU::branch },
	{ 0xB1, 5, ADDR_IZPY,			"LDA", &CPU::lda },
	{ 0xB2, 1, ADDR_INVALID, "", NULL },
	{ 0xB3, 5, ADDR_IZPY,			"LAX", &CPU::lax },
	{ 0xB4, 4, ADDR_ZPX,			"LDY", &CPU::ldy },
	{ 0xB5, 4, ADDR_ZPX,			"LDA", &CPU::lda },
	{ 0xB6, 4, ADDR_ZPY,			"LDX", &CPU::ldx },
	{ 0xB7, 4, ADDR_ZPY,			"LAX", &CPU::lax },
	{ 0xB8, 2, ADDR_IMPL,			"CLV", &CPU::clv },
	{ 0xB9, 4, ADDR_ABSY,			"LDA", &CPU::lda },
	{ 0xBA, 2, ADDR_IMPL,			"TSX", &CPU::tsx },
	{ 0xBB, 4, ADDR_INVALID, "", NULL },
	{ 0xBC, 4, ADDR_ABSX,			"LDY", &CPU::ldy },
	{ 0xBD, 4, ADDR_ABSX,			"LDA", &CPU::lda },
	{ 0xBE, 4, ADDR_ABSY,			"LDX", &CPU::ldx },
	{ 0xBF, 4, ADDR_ABSY,			"LAX", &CPU::lax },

	{ 0xC0, 2, ADDR_IMM,			"CPY", &CPU::cpy },
	{ 0xC1, 6, ADDR_IZPX,			"CMP", &CPU::cmp },
	{ 0xC2, 2, ADDR_IMM,			"NOP", &CPU::nop },
	{ 0xC3, 8, ADDR_INVALID, "", NULL },
	{ 0xC4, 3, ADDR_ZP,				"CPY", &CPU::cpy },
	{ 0xC5, 3, ADDR_ZP,				"CMP", &CPU::cmp },
	{ 0xC6, 5, ADDR_ZP,				"DEC", &CPU::dec },
	{ 0xC7, 5, ADDR_INVALID, "", NULL },
	{ 0xC8, 2, ADDR_IMPL,			"INY", &CPU::iny },
	{ 0xC9, 2, ADDR_IMM,			"CMP", &CPU::cmp },
	{ 0xCA, 2, ADDR_IMPL,			"DEX", &CPU::dex },
	{ 0xCB, 2, ADDR_INVALID, "", NULL },
	{ 0xCC, 4, ADDR_ABS,			"CPY", &CPU::cpy },
	{ 0xCD, 4, ADDR_ABS,			"CMP", &CPU::cmp },
	{ 0xCE, 6, ADDR_ABS,			"DEC", &CPU::dec },
	{ 0xCF, 6, ADDR_INVALID, "", NULL },

	{ 0xD0, 2, ADDR_REL,			"BNE", &CPU::branch },
	{ 0xD1, 5, ADDR_IZPY,			"CMP", &CPU::cmp },
	{ 0xD2, 1, ADDR_INVALID, "", NULL },
	{ 0xD3, 8, ADDR_INVALID, "", NULL },
	{ 0xD4, 4, ADDR_ZPX,			"NOP", &CPU::nop },
	{ 0xD5, 4, ADDR_ZPX,			"CMP", &CPU::cmp },
	{ 0xD6, 6, ADDR_ZPX,			"DEC", &CPU::dec },
	{ 0xD7, 6, ADDR_INVALID, "", NULL },
	{ 0xD8, 2, ADDR_IMPL,			"CLD", &CPU::cld },
	{ 0xD9, 4, ADDR_ABSY,			"CMP", &CPU::cmp },
	{ 0xDA, 2, ADDR_IMPL,			"NOP", &CPU::nop },
	{ 0xDB, 7, ADDR_INVALID, "", NULL },
	{ 0xDC, 4, ADDR_ABSX,			"NOP", &CPU::nop },
	{ 0xDD, 4, ADDR_ABSX,			"CMP", &CPU::cmp },
	{ 0xDE, 7, ADDR_ABSX,			"DEC", &CPU::dec },
	{ 0xDF, 7, ADDR_INVALID, "", NULL },

	{ 0xE0, 2, ADDR_IMM,			"CPX", &CPU::cpx },
	{ 0xE1, 6, ADDR_IZPX,			"SBC", &CPU::sbc },
	{ 0xE2, 2, ADDR_IMM,			"NOP", &CPU::nop },
	{ 0xE3, 8, ADDR_INVALID, "", NULL },
	{ 0xE4, 3, ADDR_ZP,				"CPX", &CPU::cpx },
	{ 0xE5, 3, ADDR_ZP,				"SBC", &CPU::sbc },
	{ 0xE6, 5, ADDR_ZP,				"INC", &CPU::inc },
	{ 0xE7, 5, ADDR_INVALID, "", NULL },
	{ 0xE8, 2, ADDR_IMPL,			"INX", &CPU::inx },
	{ 0xE9, 2, ADDR_IMM,			"SBC", &CPU::sbc },
	{ 0xEA, 2, ADDR_IMPL,			"NOP", &CPU::nop },
	{ 0xEB, 2, ADDR_INVALID, "", NULL },
	{ 0xEC, 4, ADDR_ABS,			"CPX", &CPU::cpx },
	{ 0xED, 4, ADDR_ABS,			"SBC", &CPU::sbc },
	{ 0xEE, 6, ADDR_ABS,			"INC", &CPU::inc },
	{ 0xEF, 6, ADDR_INVALID, "", NULL },

	{ 0xF0, 2, ADDR_REL,			"BEQ", &CPU::branch },
	{ 0xF1, 5, ADDR_IZPY,			"SBC", &CPU::sbc },
	{ 0xF2, 1, ADDR_INVALID, "", NULL },
	{ 0xF3, 8, ADDR_INVALID, "", NULL },
	{ 0xF4, 4, ADDR_ZPX,			"NOP", &CPU::nop },
	{ 0xF5, 4, ADDR_ZPX,			"SBC", &CPU::sbc },
	{ 0xF6, 6, ADDR_ZPX,			"INC", &CPU::inc },
	{ 0xF7, 6, ADDR_INVALID, "", NULL },
	{ 0xF8, 2, ADDR_IMPL,			"SED", &CPU::sed },
	{ 0xF9, 4, ADDR_ABSY,			"SBC", &CPU::sbc },
	{ 0xFA, 2, ADDR_IMPL,			"NOP", &CPU::nop },
	{ 0xFB, 7, ADDR_ABSX,			"NOP", &CPU::nop },
	{ 0xFC, 4, ADDR_ABSX,			"NOP", &CPU::nop },
	{ 0xFD, 4, ADDR_ABSX,			"SBC", &CPU::sbc },
	{ 0xFE, 7, ADDR_ABSX,			"INC", &CPU::inc },
	{ 0xFF, 7, ADDR_INVALID, "", NULL },
};