#ifndef _NES_H_
#define _NES_H_

#define NES_NTSC_CPU_CLOCK_FREQUENCY	1789773

#define NES_NMI_VECTOR					0xFFFA
#define NES_RESET_VECTOR				0xFFFC
#define NES_INTERRUPT_VECTOR			0xFFFE

#define NES_STACK_START					0x0100

#endif