#ifndef _NES_H_
#define _NES_H_

// Timing
#define NES_NTSC_MASTER_CLOCK_SPEED				21477272
#define NES_NTSC_CPU_CLOCK_DIVIDER				12
#define NES_NTSC_PPU_CLOCK_DIVIDER				4
#define NES_NTSC_CPU_CLOCK_FREQUENCY			(NES_NTSC_MASTER_CLOCK_SPEED / NES_NTSC_CPU_CLOCK_DIVIDER)
#define NES_NTSC_PPU_CLOCK_FREQUENCY			(NES_NTSC_MASTER_CLOCK_SPEED / NES_NTSC_PPU_CLOCK_DIVIDER)

#define NES_PPU_CYCLES_PER_SCANLINE				341
#define NES_PPU_VBLANK_FIRST_SCANLINE			241
#define NES_PPU_PRE_RENDER_SCANLINE				261
#define NES_PPU_LAST_SCANLINE					261

// CPU ram
#define NES_NMI_VECTOR							0xFFFA
#define NES_RESET_VECTOR						0xFFFC
#define NES_IRQ_VECTOR							0xFFFE

#define NES_STACK_START							0x0100

#define NES_CPU_RAM_SIZE						0x0800

// PPU ram
#define NES_PPU_RAM_SIZE						0x800
#define NES_PPU_RAM_ADDRESS_MASK				0x7FF

#define NES_PPU_PATTERN0						0x0000
#define NES_PPU_PATTERN1						0x1000

#define NES_PPU_NAMETABLE0						0x2000
#define NES_PPU_NAMETABLE1						0x2400
#define NES_PPU_NAMETABLE2						0x2800
#define NES_PPU_NAMETABLE3						0x2C00
#define NES_PPU_ATTRIBUTE_OFFSET				0x00C0

#define NES_PPU_PALETTE_RAM						0x3F00
#define NES_PPU_PALETTE_RAM_SIZE				0x20
#define NES_PPU_PALETTE_RAM_ADDRESS_MASK		(NES_PPU_PALETTE_RAM_SIZE - 1)

// PPU sprites
#define NES_PPU_PRIMARY_OAM_SIZE				0xFF
#define NES_PPU_PRIMARY_OAM_SPRITES				0x40

#define NES_PPU_SECONDARY_OAM_SIZE				0x20
#define NES_PPU_SECONDARY_OAM_SPRITES			0x08

#define NES_PPU_SPRITE_SIZE						0x04

#define NES_PPU_SPRITE_ATTRIBUTE_BIT_PRIORITY	5
#define NES_PPU_SPRITE_ATTRIBUTE_BIT_FLIP_X		6
#define NES_PPU_SPRITE_ATTRIBUTE_BIT_FLIP_Y		7

// PPU registers
#define NES_PPU_STATUS_BIT_VBLANK				7
#define NES_PPU_STATUS_BIT_SPRITE0_HIT			6
#define NES_PPU_STATUS_BIT_SPRITE_OVERFLOW		5

#define NES_PPU_CONTROL_BIT_NAMETABLE_SELECT	0
#define NES_PPU_CONTROL_BIT_INCREMENT_MODE		2
#define NES_PPU_CONTROL_BIT_SPRITE_ADDRESS		3
#define NES_PPU_CONTROL_BIT_BACKGROUND_ADDRESS	4
#define NES_PPU_CONTROL_BIT_SPRITE_HEIGHT		5
#define NES_PPU_CONTROL_BIT_MODE_SELECT			6
#define NES_PPU_CONTROL_BIT_NMI_ENABLE			7

#define NES_PPU_MASK_BIT_GREYSCALE				0
#define NES_PPU_MASK_BIT_COL0_BACKGROUND		1
#define NES_PPU_MASK_BIT_COL0_SPRITES			2
#define NES_PPU_MASK_BIT_BACKGROUND				3
#define NES_PPU_MASK_BIT_SPRITES				4
#define NES_PPU_MASK_BIT_EMPHASIZE_RED			5
#define NES_PPU_MASK_BIT_EMPHASIZE_GREEN		6
#define NES_PPU_MASK_BIT_EMPHASIZE_BLUE			7

// PPU video properties
#define NES_FRAME_WIDTH							256
#define NES_FRAME_HEIGHT						240

#define NES_PPU_TILE_SIZE						8

#define NES_PPU_PATTERN_TABLE_TILES_PER_ROW		16
#define NES_PPU_PATTERN_TABLE_TILES_PER_COLUMN	16
#define NES_PPU_PATTERN_TABLE_WIDTH				(NES_PPU_PATTERN_TABLE_TILES_PER_COLUMN * NES_PPU_TILE_SIZE)
#define NES_PPU_PATTERN_TABLE_HEIGHT			(NES_PPU_PATTERN_TABLE_TILES_PER_ROW * NES_PPU_TILE_SIZE)

#define NES_PPU_NAMETABLE_TILES_PER_ROW			32
#define NES_PPU_NAMETABLE_TILES_PER_COLUMN		30
#define NES_PPU_NAMETABLE_WIDTH					(NES_PPU_NAMETABLE_TILES_PER_ROW * NES_PPU_TILE_SIZE)
#define NES_PPU_NAMETABLE_HEIGHT				(NES_PPU_NAMETABLE_TILES_PER_COLUMN * NES_PPU_TILE_SIZE)

#endif